In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("./OFZ Data - Dataset.csv")
display(data)

,Index,Название,Начало Торгов,Погашение,Купон,Периодичность,ISIN,start,end,Price,days_to_maturity,moex_ytm,years_to_maturity,Date,Rate,Inflation,Observed Inflation,Expected inflation 1y
0,5,26208,07.03.2012,27.02.2019,7.5,2,SU26208RMFS7,2012-03-07,2019-02-27,101.11525,422,6.6351,1.156164,2018-01-01,7.75,2.50,10.0,8.7
1,12,26216,13.11.2013,15.05.2019,6.7,2,SU26216RMFS0,2013-11-13,2019-05-15,100.04750,499,6.8103,1.367123,2018-01-01,7.75,2.50,10.0,8.7
2,7,26210,19.12.2012,11.12.2019,6.8,2,SU26210RMFS3,2012-12-19,2019-12-11,100.11450,709,6.8798,1.942466,2018-01-01,7.75,2.50,10.0,8.7
3,10,26214,23.10.2013,27.05.2020,6.4,2,SU26214RMFS5,2013-10-23,2020-05-27,99.06450,877,6.9665,2.402740,2018-01-01,7.75,2.50,10.0,8.7
4,3,26205,13.02.2012,14.04.2021,7.6,2,SU26205RMFS3,2012-02-13,2021-04-14,102.45550,1199,6.8859,3.284932,2018-01-01,7.75,2.50,10.0,8.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1538,17,26233,13.05.2020,18.07.2035,6.1,2,SU26233RMFS5,2020-05-13,2035-07-18,65.74400,4247,11.8467,11.635616,2023-12-01,15.00,7.48,15.1,12.2
1539,24,26240,30.06.2021,30.07.2036,7.0,2,SU26240RMFS0,2021-06-30,2036-07-30,70.24550,4625,11.8485,12.671233,2023-12-01,15.00,7.48,15.1,12.2
1540,27,26243,21.06.2023,19.05.2038,9.8,2,SU26243RMFS4,2023-06-21,2038-05-19,87.85850,5283,11.8803,14.473973,2023-12-01,15.00,7.48,15.1,12.2
1541,14,26230,19.06.2019,16.03.2039,7.7,2,SU26230RMFS1,2019-06-19,2039-03-16,72.62575,5584,11.8831,15.298630,2023-12-01,15.00,7.48,15.1,12.2
1542,22,26238,23.06.2021,15.05.2041,7.1,2,SU26238RMFS4,2021-06-23,2041-05-15,67.05400,6375,11.8517,17.465753,2023-12-01,15.00,7.48,15.1,12.2

0